from __future__ import annotations

from .agents import AGENTS_MD, AGENTS_SKILLS_DIR, TARGET_AGENTS
from .claude import AGENT_CLAUDE, CLAUDE_DIR, CLAUDE_MD, CLAUDE_MD_PATH, CLAUDE_SKILLS_DIR
from .codex import AGENT_CODEX, CODEX_DIR
from .copilot import (
    AGENT_COPILOT,
    COPILOT_INSTRUCTIONS_DIR,
    COPILOT_INSTRUCTIONS_MD,
    COPILOT_SKILLS_DIR,
    EXT_INSTRUCTIONS_MD,
)
from .cursor import AGENT_CURSOR, CURSOR_DIR, CURSOR_RULES_FILE, EXT_MDC
from .gemini import AGENT_GEMINI, GEMINI_DIR, GEMINI_MD
from .shared import (
    AGENT_NAMES,
    AGENT_PROJECT_SIGNALS,
    AGENTS_TARGET_COVERS,
    SOURCE_PROJECT,
    VALID_RULE_TARGET_IDS,
    VALID_SKILL_TARGET_IDS,
)

__all__ = [
    "AGENT_CLAUDE",
    "AGENT_CODEX",
    "AGENT_COPILOT",
    "AGENT_CURSOR",
    "AGENT_GEMINI",
    "AGENT_NAMES",
    "AGENT_PROJECT_SIGNALS",
    "AGENTS_MD",
    "AGENTS_SKILLS_DIR",
    "AGENTS_TARGET_COVERS",
    "CLAUDE_DIR",
    "CLAUDE_MD",
    "CLAUDE_MD_PATH",
    "CLAUDE_SKILLS_DIR",
    "CODEX_DIR",
    "COPILOT_INSTRUCTIONS_DIR",
    "COPILOT_INSTRUCTIONS_MD",
    "COPILOT_SKILLS_DIR",
    "CURSOR_DIR",
    "CURSOR_RULES_FILE",
    "EXT_INSTRUCTIONS_MD",
    "EXT_MDC",
    "GEMINI_DIR",
    "GEMINI_MD",
    "SOURCE_PROJECT",
    "TARGET_AGENTS",
    "VALID_RULE_TARGET_IDS",
    "VALID_SKILL_TARGET_IDS",
]
